version: '3.8'

services:
  node_app:
    build: ./otros/servicio/.
    ports:
      - "3000:3000"


  mariadb:
    image: mariadb
    command: --default-authentication-plugin=ey%2024#database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ey%2024#database
      MYSQL_DATABASE: admin
      MYSQL_USER: eyuser
      MYSQL_PASSWORD: passwordey1234
    ports:
      - "3310:3306"
    volumes:
      - ./volumenes/mariadb_data:/var/lib/mysql
      - ./volumenes/initDB.sql:/docker-entrypoint-initdb.d/1.sql  # Montar el directorio con los archivos SQL

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: eyuserroot
      MONGO_INITDB_ROOT_PASSWORD: passwordey1234
      MONGO_INITDB_DATABASE: root-db
    ports:
        - 27017:27017
    volumes:
        - ./volumenes/mongodb_data:/data/db       
        - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  mariadb_data:
  mongodb_data: